### ISSUE TITLE
Error in get data if size it is greater than the total number of records that we have in databases.

### ISSUE THREAD

**Issue by thisismz** [morkid/paginate#10]
Hello,
The issue at hand is as follows.
Consider the following code:
```
query := fmt.Sprintf(`page=%d&size=%d`, 1, 5)
req := &http.Request{
    Method: "GET",
    URL: &url.URL{
        RawQuery: query,
    },
}
page := Pagination.With(resp).Request(req).Response(&result)
```
If the total number of records in our database is only **4**, we won't receive anything in the response.
Please provide a solution. Thank you.

**Comment by morkid** [comment]
page always starts at 0. you can change page to 0 instead of 1
