### ISSUE TITLE
MySQL syntax near ''\' ) )'

### ISSUE THREAD

**Issue by krewllobster** [morkid/paginate#2]
When passing a filter array like `[["make", "like", "a"]]` I am receiving the following error:

```
.../go/pkg/mod/github.com/morkid/paginate@v1.1.3/paginate.go:201 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''\' ) )' at line 1
[3.546ms] [rows:0] SELECT count(1) FROM (SELECT * FROM `equipment` WHERE `equipment`.`deleted_at` IS NULL) AS s WHERE ( ( `make` LIKE '%a%' ESCAPE '\' ) )
```

The filters work fine when it is just `[["make","a"]]` but that only returns exact matches. Any thoughts? Gorm database initialization looks like:

```
Database, _ = gorm.Open(mysql.Open(dsn), &gorm.Config{
	Logger: logger.Default.LogMode(logger.Info),
})
```

**Comment by morkid** [comment]
hi @krewllobster, thanks for reporting.
sorry, it's my fault. I've missed something for MySQL. please enjoy the next version.

**Comment by krewllobster** [comment]
No worries, thanks for addressing so quickly!
