### ISSUE TITLE
Sorting using nested field

### ISSUE THREAD

**Issue by gipsh** [morkid/paginate#5]
Hi, on posgres im trying to sort from a nested field from a join query.

- on the querystring i have `?sort=Country.name`
- on the query the clause look ok, the name is correctly camelized 
`LEFT JOIN \"addresses\" \"Address\" ON \"accounts\".\"address_id\" = \"Address\".\"id\" WHERE \"accounts\".\"deleted_at\" IS NULL) AS s ORDER BY Country__name ASC LIMIT 50` 
- and also the Country_name column name is being generated correctly `"Country\".\"name\" AS \"Country__name\"`

Still is throwing:
`"error": "ERROR: column \"country__name\" does not exist (SQLSTATE 42703)"`

I think the issue is on the generated query, the `order by` shouldnt be inside the inner select ??

right now is doing: 
SELECT count(*) FROM  (SELECT........ ) as S **ORDER BY Country_name ASC**

shouldnt be like this ??
SELECT count(*) FROM  (SELECT........ **ORDER BY Country_name ASC**) as S 

Thanks!!

**Comment by morkid** [comment]
Have you try this instead?
```
SELECT count(*) FROM (...) as "Country"
```

replace alias **S** with **"Country"** *(for postgresql always use doublequotes to wrap table name to avoid lowercase conversion)*
