### ISSUE TITLE
Filters can't apply dot (.) 

### ISSUE THREAD

**Issue by agambondan** [morkid/paginate#8]
example request : https://localhost:9900/api/v1/books?filters=[%22tr.id%22,%22bukhari%22]
![image](https://github.com/morkid/paginate/assets/37768596/1b4e9620-0f6b-4f5e-960c-97920e7abf4f)

![image](https://github.com/morkid/paginate/assets/37768596/77e6e1b3-ea01-4e13-b0ad-3409f714eb4e)
can you give a key other than the dot value, so I can filter by lowercase reference.

**Comment by morkid** [comment]
hi @agambondan , thanks for the report. could you please to provide the code related to the error.

example:

```go
query := db.Model(...) <====
pg.With(query).Request(req).Response(res)
```
